-- Generated by scripts/generate-problems-sql.mjs
-- Source: problems.txt

begin;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 1, 'single_choice', '中国共产党第二十届中央委员会第四次全体会议于何时在北京举行？', '{"A":"2025年10月18日至21日","B":"2025年10月20日至23日","C":"2025年10月22日至25日","D":"2025年10月25日至28日"}'::jsonb, '{"choices":["B"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 2, 'single_choice', '党的二十届四中全会审议通过了哪一份重要文件？', '{"A":"《中共中央关于深化党和国家机构改革的决定》","B":"《中共中央关于制定国民经济和社会发展第十五个五年规划的建议》","C":"《中共中央关于党的百年奋斗重大成就和历史经验的决议》","D":"《中共中央关于坚持和完善中国特色社会主义制度、推进国家治理体系和治理能力现代化若干重大问题的决定》"}'::jsonb, '{"choices":["B"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 3, 'single_choice', '“十五五”时期在我国社会主义现代化建设进程中的定位是什么？', '{"A":"起步阶段","B":"基本实现社会主义现代化夯实基础、全面发力的关键时期","C":"收尾阶段","D":"调整阶段"}'::jsonb, '{"choices":["B"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 4, 'single_choice', '全会指出，“十四五”时期我国的发展历程是？', '{"A":"平稳顺利","B":"极不寻常、极不平凡","C":"充满机遇","D":"挑战重重"}'::jsonb, '{"choices":["B"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 5, 'single_choice', '全会强调，“十五五”时期经济社会发展的主题是什么？', '{"A":"高速增长","B":"高质量发展","C":"稳定发展","D":"创新发展"}'::jsonb, '{"choices":["B"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 6, 'single_choice', '全会强调，“十五五”时期经济社会发展的根本动力是什么？', '{"A":"投资拉动","B":"改革创新","C":"消费驱动","D":"出口导向"}'::jsonb, '{"choices":["B"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 7, 'single_choice', '建设现代化产业体系，要坚持把发展经济的着力点放在哪里？', '{"A":"虚拟经济","B":"实体经济","C":"数字经济","D":"服务经济"}'::jsonb, '{"choices":["B"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 8, 'single_choice', '构建新发展格局必须坚持的战略基点是什么？', '{"A":"扩大内需","B":"深化供给侧结构性改革","C":"高水平对外开放","D":"科技创新"}'::jsonb, '{"choices":["A"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 9, 'single_choice', '全会提出，加大保障和改善民生力度，其出发点和落脚点是什么？', '{"A":"全面建成社会主义现代化强国","B":"推动全体人民共同富裕","C":"实现人民对美好生活的向往","D":"解决好人民群众急难愁盼问题"}'::jsonb, '{"choices":["C"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 10, 'single_choice', '全会指出，推进中国式现代化必须把什么摆在更加突出位置？', '{"A":"改革","B":"速度","C":"规模","D":"负债"}'::jsonb, '{"choices":["A"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 11, 'single_choice', '全会提出，要稳步扩大什么，这是新时代对外开放的鲜明特征？', '{"A":"出口规模","B":"制度型开放","C":"招商引资范围","D":"开发区数量"}'::jsonb, '{"choices":["B"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 12, 'single_choice', '全会强调，坚持以什么引领社会革命？', '{"A":"党的自我革命","B":"全面从严治党","C":"改革开放","D":"科技创新"}'::jsonb, '{"choices":["A"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 13, 'single_choice', '以下哪项是“十五五”时期经济社会发展的主要目标之一？', '{"A":"经济保持中高速增长","B":"高质量发展取得显著成效","C":"各方面制度更加成熟更加定型","D":"实现全面小康"}'::jsonb, '{"choices":["B"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 14, 'single_choice', '全会提出，加快形成新质生产力，要抓住新一轮什么历史机遇？', '{"A":"科技革命和产业变革","B":"能源革命和贸易变革","C":"金融革命和消费变革","D":"土地革命和城乡变革"}'::jsonb, '{"choices":["A"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 15, 'single_choice', '推进美丽中国建设，要以什么为核心牵引？', '{"A":"污染防治攻坚战","B":"碳达峰碳中和","C":"绿色消费","D":"新能源建设"}'::jsonb, '{"choices":["B"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 16, 'single_choice', '全会对“十四五”时期成就的评价中，不包括以下哪一项？', '{"A":"经济实力、科技实力、综合国力跃上新台阶","B":"中国式现代化迈出新的坚实步伐","C":"第二个百年奋斗目标新征程实现良好开局","D":"我国已经进入中等发达国家水平"}'::jsonb, '{"choices":["D"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 17, 'single_choice', '下列哪项未被全会列为“十五五”时期民生建设重点？', '{"A":"健全社会保障体系","B":"深化医药卫生体制改革","C":"全面取消个人医保缴费","D":"完善收入分配制度"}'::jsonb, '{"choices":["C"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 18, 'single_choice', '构建高水平社会主义市场经济体制，要聚焦完善哪些方面？
·①完善产权保护②市场准入负面清单③公平竞争审查④要素市场化配置⑤宏观经济治理', '{"A":"①②③④","B":"①②④⑤","C":"①③④⑤","D":"②③④⑤"}'::jsonb, '{"choices":["C"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 19, 'single_choice', '下列哪项不是全会提出的“十五五”时期生态文明建设重点？', '{"A":"深入推进污染防治攻坚","B":"加快建设新型能源体系","C":"全面取消化石能源消费","D":"积极稳妥推进碳达峰"}'::jsonb, '{"choices":["C"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 20, 'single_choice', '“十五五”时期要求居民收入增长与什么同步？', '{"A":"物价上涨","B":"经济增长","C":"人口增长","D":"财政收入增长"}'::jsonb, '{"choices":["B"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 21, 'single_choice', '现代化产业体系建设要求全链条推动哪些领域关键核心技术攻关？', '{"A":"房地产、金融、商贸","B":"集成电路、工业母机、高端仪器、基础软件、先进材料、生物制造","C":"农业、轻工业、服务业","D":"教育、医疗、文化"}'::jsonb, '{"choices":["B"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 22, 'single_choice', '“十五五”时期要求内需在经济增长中发挥什么作用？', '{"A":"辅助作用","B":"主动力作用","C":"平衡作用","D":"调节作用"}'::jsonb, '{"choices":["B"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 23, 'single_choice', '全会提出，发挥哪些战略的叠加效应，优化重大生产力布局？', '{"A":"区域协调发展战略、区域重大战略、主体功能区战略、新型城镇化战略","B":"乡村振兴战略、创新驱动发展战略","C":"可持续发展战略、人才强国战略","D":"军民融合发展战略、就业优先战略"}'::jsonb, '{"choices":["A"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 24, 'single_choice', '全会指出，解决关键核心技术“卡脖子”问题，需要强化什么导向？', '{"A":"集成创新","B":"引进消化吸收再创新","C":"原始创新","D":"商业模式创新"}'::jsonb, '{"choices":["C"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 25, 'single_choice', '出席党的二十届四中全会的中央委员有多少人？', '{"A":"165人","B":"168人","C":"170人","D":"172人"}'::jsonb, '{"choices":["B"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 26, 'single_choice', '党的二十届四中全会由谁主持？', '{"A":"习近平","B":"李强","C":"中央政治局","D":"中央委员会"}'::jsonb, '{"choices":["C"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 27, 'single_choice', '“十四五”时期，我国经受住了哪一重大冲击？', '{"A":"金融危机","B":"世纪疫情","C":"严重自然灾害","D":"国际格局剧变"}'::jsonb, '{"choices":["B"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 28, 'single_choice', '全会提出，要畅通什么渠道，提高人民生活品质？', '{"A":"商品流通渠道","B":"信息传播渠道","C":"社会流动渠道","D":"意见反馈渠道"}'::jsonb, '{"choices":["C"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 29, 'single_choice', '党的二十届四中全会审议通过了哪一份重要规划建议？', '{"A":"《中共中央关于制定国民经济和社会发展第十四个五年规划的建议》","B":"《中共中央关于制定国民经济和社会发展第十五个五年规划的建议》","C":"《中共中央关于制定国民经济和社会发展第十六个五年规划的建议》","D":"《中共中央关于深化党和国家机构改革的决定》"}'::jsonb, '{"choices":["B"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 30, 'single_choice', '全会强调，“十五五”时期经济社会发展的根本动力是什么？', '{"A":"投资与出口拉动","B":"要素投入驱动","C":"全面深化改革（改革创新）","D":"政策刺激"}'::jsonb, '{"choices":["C"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 31, 'single_choice', '全会对我国能源转型和绿色发展的要求是什么？', '{"A":"立即全面取消化石能源消费","B":"积极稳妥推进碳达峰碳中和，建设新型能源体系","C":"暂停所有高耗能产业发展","D":"完全依赖可再生能源"}'::jsonb, '{"choices":["B"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 32, 'single_choice', '实现社会主义现代化的过程具有什么特点？', '{"A":"一个可以一蹴而就、线性发展的过程","B":"一个阶梯式递进、不断发展进步、需要不懈奋斗的过程","C":"一个主要依靠外部力量推动的过程","D":"一个已经接近完成的过程"}'::jsonb, '{"choices":["B"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 33, 'single_choice', '“十五五”规划《建议》是由谁主持审议通过的？', '{"A":"国务院","B":"全国人民代表大会","C":"中央政治局","D":"全国政协"}'::jsonb, '{"choices":["C"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 34, 'single_choice', '建设强大国内市场，要坚持紧密结合，并以（    ）引领新供给。', '{"A":"惠民生与促消费；新需求","B":"稳就业与稳物价；新技术","C":"扩大投资与扩大出口；新业态","D":"减税降费与放松管制；新资本"}'::jsonb, '{"choices":["A"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 35, 'single_choice', '加快农业农村现代化，全会提出要把（    ）作为全党工作重中之重，并推动农村基本具备。', '{"A":"乡村振兴；现代生活条件","B":"粮食安全；农业机械普及","C":"农民增收；5G网络覆盖","D":"土地制度改革；集中居住条件"}'::jsonb, '{"choices":["A"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 36, 'single_choice', '党的二十届四中全会决定，增补为中共中央军事委员会副主席的是（    ）。', '{"A":"何卫东","B":"张升民","C":"苗华","D":"王春宁"}'::jsonb, '{"choices":["B"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 37, 'single_choice', '推进国家安全体系和能力现代化，要重点加强:
1经济安全
2网络数据安全
3生物安全
4资源安全
5太空安全。
全会公报明确列出的是（     ）。', '{"A":"1  2  3  4","B":"1  2  3  5","C":"1  2  4  5","D":"全部列出"}'::jsonb, '{"choices":["A"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 38, 'single_choice', '全面绿色转型要协同推进:
1降碳
2减污
3扩绿
4增长
5节能
下列组合完全准确的是（    ）', '{"A":"1  2  3  4","B":"1  2  3  5","C":"1  2  4  5","D":"2  3  4  5"}'::jsonb, '{"choices":["A"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 39, 'single_choice', '党的二十届四中全会号召，全国各族人民要更加紧密团结在（    ）。', '{"A":"以习近平同志为核心的党中央周围","B":"以经济建设为中心的旗帜下","C":"以改革开放为动力的征程上","D":"以共同富裕为目标的奋斗中"}'::jsonb, '{"choices":["A"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 40, 'single_choice', '推进区域协调发展，要发挥（    ）叠加效应，并优化（    ）布局。', '{"A":"经济高速增长目标","B":"全年经济社会发展目标","C":"财政收入目标","D":"投资增长目标"}'::jsonb, '{"choices":["B"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 42, 'single_choice', '党的二十届四中全会强调，推进中国式现代化必须敢于斗争、善于斗争，勇于面对（    ）', '{"A":"一般性考验","B":"风高浪急甚至惊涛骇浪的重大考验","C":"技术性挑战","D":"周期性波动"}'::jsonb, '{"choices":["B"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 43, 'single_choice', '党的二十届四中全会强调，实现社会主义现代化是一个阶梯式递进的历史过程，需要: （    ）', '{"A":"短期内集中突破","B":"不懈努力、接续奋斗","C":"依靠外部力量推动","D":"以城市化为核心路径"}'::jsonb, '{"choices":["B"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 44, 'single_choice', '全会认为，我国发展当前处于（    ）的阶段', '{"A":"战略机遇期","B":"风险高发期","C":"战略机遇和风险挑战并存","D":"全面转型期"}'::jsonb, '{"choices":["C"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 45, 'single_choice', '党的二十届四中全会指出，我国发展仍处于战略机遇期，但也面临: （    ）', '{"A":"单一风险挑战","B":"战略机遇与风险挑战并存","C":"完全可控的外部环境","D":"经济增长放缓为主"}'::jsonb, '{"choices":["B"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 46, 'single_choice', '推动新质生产力发展，必须抢占（    ），并推动（    ）深度融合。', '{"A":"科技发展制高点；科技创新与产业创新","B":"国际市场份额；虚拟经济与实体经济","C":"全球资源配置权；教育与市场","D":"产业链高端；制造业与金融业"}'::jsonb, '{"choices":["A"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 47, 'single_choice', '党的二十届四中全会提出，推动全体人民共同富裕要: （    ）', '{"A":"一步到位","B":"先富带动后富","C":"稳步推进","D":"以城市为中心"}'::jsonb, '{"choices":["C"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 48, 'single_choice', '党的二十届四中全会提出，建设美丽中国必须牢固树立的理念是: （    ）', '{"A":"工业优先","B":"绿水青山就是金山银山","C":"城市化主导","D":"高速增长优先"}'::jsonb, '{"choices":["B"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 49, 'single_choice', '党的二十届四中全会指出，我国长期向好的基本趋势（    ）', '{"A":"已经改变","B":"没有变","C":"正在逆转","D":"难以判断"}'::jsonb, '{"choices":["B"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 50, 'single_choice', '全会强调，推动经济实现质的有效提升和量的合理增长，必须以（    ）什么为中心？', '{"A":"政治建设","B":"文化建设","C":"经济建设","D":"社会建设"}'::jsonb, '{"choices":["C"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 51, 'single_choice', '以下哪项不是“十五五”时期经济社会发展必须遵循的原则？ （    ）', '{"A":"坚持党的全面领导","B":"坚持人民至上","C":"坚持市场优先","D":"坚持高质量发展"}'::jsonb, '{"choices":["C"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 52, 'single_choice', '全会提出，构建现代化产业体系要坚持（    ）方向，并以（    ）为骨干。', '{"A":"智能化、绿色化、融合化；现代服务业","B":"高端化、数字化、国际化；战略性新兴产业","C":"智能化、绿色化、融合化；先进制造业","D":"绿色化、服务化、虚拟化；数字经济"}'::jsonb, '{"choices":["C"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 53, 'single_choice', '全会指出，国家安全是中国式现代化: （    ）', '{"A":"最终目标","B":"行稳致远的重要基础","C":"经济建设的补充","D":"外交工作的延伸"}'::jsonb, '{"choices":["B"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 54, 'single_choice', '全会提出，推进中国式现代化的根本保障是（    ）', '{"A":"教育","B":"科技","C":"党的领导","D":"市场机制"}'::jsonb, '{"choices":["C"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 55, 'single_choice', '党的二十届四中全会提出，要增强国内大循环的（    ）', '{"A":"外部依赖性","B":"内生动力和可靠性","C":"出口导向性","D":"投资拉动性"}'::jsonb, '{"choices":["B"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 56, 'single_choice', '全会提出，现代化产业体系的骨干是: （    ）', '{"A":"服务业","B":"数字经济","C":"先进制造业","D":"房地产"}'::jsonb, '{"choices":["C"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 57, 'single_choice', '党的二十届四中全会提出，推动新质生产力发展的关键是: （    ）', '{"A":"扩大出口","B":"科技创新","C":"降低税收","D":"增加劳动力"}'::jsonb, '{"choices":["B"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 58, 'single_choice', '全会提出，保障和改善民生的基本原则是: （    ）', '{"A":"尽力而为、量力而行","B":"全民免费、全面覆盖","C":"市场主导、政府辅助","D":"以城市为重点"}'::jsonb, '{"choices":["A"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 59, 'single_choice', '下列哪项是“增强国内大循环内生动力和可靠性”的直接举措？ （    ）', '{"A":"织牢社会保障安全网","B":"大力提振消费，扩大有效投资","C":"加强国防和军队现代化建设","D":"做好稳外贸工作"}'::jsonb, '{"choices":["B"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 60, 'single_choice', '构建新发展格局的战略基点是（    ），关键在于增强（    ）。', '{"A":"扩大内需；国内大循环内生动力和可靠性","B":"扩大出口；国际市场竞争力","C":"提高消费；居民储蓄率","D":"稳定投资；政府财政支出能力"}'::jsonb, '{"choices":["A"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 61, 'single_choice', '推进美丽中国建设，要以（    ）为牵引，并协同推进（    ）。', '{"A":"碳达峰碳中和；降碳、减污、扩绿、增长","B":"绿色消费；节能、减排、循环、发展","C":"新能源建设；控煤、限排、绿化、提效","D":"环境治理；节能、降耗、绿化、增长"}'::jsonb, '{"choices":["A"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 62, 'single_choice', '提高人民生活品质，要完善（    ）制度体系，并畅通（    ）渠道。', '{"A":"基本公共服务；社会流动","B":"商业保险；人才落户","C":"税收减免；就业培训","D":"住房保障；消费信贷"}'::jsonb, '{"choices":["A"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 63, 'single_choice', '保障和改善民生要坚持尽力而为、量力而行原则，并重点加强民生建设。 （    ）', '{"A":"普惠性、基础性、兜底性","B":"高端化、个性化、智能化","C":"选择性、竞争性、效率性","D":"城市型、消费型、数字型"}'::jsonb, '{"choices":["A"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 64, 'single_choice', '公报指出，我国发展仍处于长期向好的基本趋势，这一判断的根本依据是“四个优势”更加彰显，下列不属于“四个优势”的是（    ）。', '{"A":"超大规模市场","B":"完整产业体系","C":"丰富人才资源","D":"全球资源配置权"}'::jsonb, '{"choices":["D"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 65, 'single_choice', '全会提出，到2035年人均国内生产总值达到（    ）水平，人民生活更加（    ）。', '{"A":"中等发达国家；幸福美好","B":"高收入国家；富裕富足","C":"中等偏上国家；安定有序","D":"发达国家；全面免费"}'::jsonb, '{"choices":["A"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 66, 'single_choice', '全会强调，推进中国式现代化必须继续做到:
1坚持党的全面领导
2坚持人民至上
3坚持高质量发展
4坚持全面深化改革
5坚持有效市场与有为政府相结合。
下列选项中，哪一项属于“必须遵循的原则”且表述完全准确？ （    ）', '{"A":"1  2  3  4","B":"1  2  3  5","C":"1  3  4  5","D":"1  2  3  4  5"}'::jsonb, '{"choices":["D"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 67, 'single_choice', '全会强调，‘十五五''时期经济社会发展，要坚持（    ）工作总基调。', '{"A":"稳中求进","B":"稳中求快","C":"稳中求好","D":"稳中求新"}'::jsonb, '{"choices":["A"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 68, 'single_choice', '中国共产党第二十届中央委员会第四次全体会议于2025年10月20日至23日在北京举行。全会指出，十五五时期经济社会发展要推动经济实现（     ）和（     ）推动（     ）全体人民共同富裕迈出坚实步伐。', '{"A":"质量提升、规模扩大、经济社会全面发展","B":"质量优化、数量增长、社会文明程度提升","C":"高质量发展、高速度增长、生活品质不断提高","D":"质的有效提升、量的合理增长、人的全面发展"}'::jsonb, '{"choices":["D"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 69, 'single_choice', '全会对“十五五”时期发展环境的基本判断是（     ）。', '{"A":"风险挑战已完全克服","B":"战略机遇和风险挑战并存","C":"进入一帆风顺的发展阶段","D":"不确定难预料因素显著减少"}'::jsonb, '{"choices":["B"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 70, 'single_choice', '加快农业农村现代化，要坚持把（     ）作为重中之重，持续巩固拓展（    ）成果，推动农村基本具备', '{"A":"农民增收；土地改革；5G覆盖","B":"粮食安全；乡村振兴；集中居住","C":"解决好“三农”问题；脱贫攻坚；现代生活条件","D":"县域经济；集体产权；智慧农业"}'::jsonb, '{"choices":["C"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 71, 'single_choice', '党的二十届四中全会强调，推进中国式现代化要把（     ）转化为强大力量。', '{"A":"进一步全面深化改革的战略部署","B":"国际贸易份额提升","C":"人口规模优势","D":"土地财政资源"}'::jsonb, '{"choices":["A"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 72, 'single_choice', '下列关于“制度型开放”表述正确的是（     ）', '{"A":"仅适用于服务业","B":"以开放促改革促发展","C":"取消所有外资准入限制","D":"只针对发达国家"}'::jsonb, '{"choices":["B"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 73, 'single_choice', '推进区域协调发展，要发挥（    ）叠加效应，并构建（    ）的区域经济布局。', '{"B":"三大战略；均衡分布、平均增速","C":"五大战略；沿海优先、梯度转移","D":"六大战略；城市集群、单一中心"}'::jsonb, '{"choices":["A"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 74, 'single_choice', '加快制造强国建设，要保持制造业，（      ），并推动传统产业（     ）。', '{"A":"合理比重；优化提升","B":"快速增长；规模扩张","C":"高利润；多元经营","D":"出口导向；全球布局"}'::jsonb, '{"choices":["A"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 75, 'single_choice', '加快实现建军一百年奋斗目标，要推进政治建军、改革强军、（       ）、人才强军、（     ）。', '{"A":"科技强军；依法治军","B":"装备强军；文化治军","C":"经济强军；纪律治军","D":"外交强军；思想治军"}'::jsonb, '{"choices":["A"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 76, 'single_choice', '下列哪项不是“十五五”时期文化建设目标。 （    ）', '{"A":"社会文明程度明显提升","B":"文化产业产值翻番","C":"中华文明传播力影响力提升","D":"社会主义核心价值观广泛弘扬"}'::jsonb, '{"choices":["B"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 77, 'single_choice', '党的二十届四中全会指出，进一步全面深化改革的出发点和落脚点是（    ）。', '{"A":"促进社会公平正义、增进人民祉","B":"保持GDP中高增速","C":"扩大外汇储备","D":"实现贸易顺差平衡"}'::jsonb, '{"choices":["A"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 78, 'single_choice', '扎实推动高质量发展，必须以动力。 （    ）为主题，以（    ）为根本', '{"A":"供给侧结构性改革；开放","B":"高质量发展；改革创新","C":"现代化产业体系；投资","D":"新发展格局；消费"}'::jsonb, '{"choices":["B"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 79, 'single_choice', '加快绿色转型，要协同推进降碳、减污、（    ） ，并筑牢（    ）屏障。', '{"A":"扩绿增长；生态安全","B":"节能提效；资源安全","C":"循环利用；能源安全","D":"生态修复；经济安全"}'::jsonb, '{"choices":["A"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 80, 'single_choice', '全会提出，“十五五”时期经济社会发展的主要目标，共有（    ）项。', '{"A":"五","B":"六","C":"七","D":"八"}'::jsonb, '{"choices":["C"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 81, 'single_choice', '全会提出，加快形成新质生产力，要抓住新一轮历史机遇，提升国家创新体系整体效能。（    ）', '{"A":"科技革命；产业变革","B":"能源革命；贸易变革","C":"金融革命；消费变革","D":"土地革命；城乡变革"}'::jsonb, '{"choices":["A"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 82, 'single_choice', '全会强调，全党要深刻领悟（    ）的决定性意义。', '{"A":"两个维护","B":"两个确立","C":"四个意识","D":"四个自信"}'::jsonb, '{"choices":["B"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 83, 'single_choice', '推进国家安全体系和能力现代化，要坚定不移贯彻社会治理之路，确保社会（     ）
走（        ）又井然有序。', '{"A":"总体国家安全观；中国特色社会主义；生机勃勃","B":"新安全格局；数字化；稳定可控","C":"全球安全倡议；法治化；平均分配","D":"传统安全观；自治化；低度活跃"}'::jsonb, '{"choices":["A"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 84, 'single_choice', '2025年10月20日至23日，党的二十届四中全会在北京召开， 研究制定“十五五”规划建议。下列关于习近平如何准确把握阶段性要求，科学谋划“十五五”相关阐述说法不正确的是（    ）。', '{"A":"以数字创新为引领、以智能经济为根基","B":"加快建设现代化产业体系","C":"坚持全面推进传统产业转型升级、积极发展新兴产业、超前布局未来产业并举","D":"必须把因地制宜发展新质生产力摆在更加突出的战略位置"}'::jsonb, '{"choices":["A"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 85, 'single_choice', '2025年10月20日至23日，党的二十届四中全会在北京召开， 研究制定“十五五”规划建议。科学谋划“十五五”要坚定不移办好自己的事，坚定不移扩大高水平对外开放，下列有关说法正确的有几项（    ）。
1全面推动高质量发展
2多措并举稳就业、稳企业、稳市场、稳预期
3有效稳住经济基本盘
4加快构建新发展格局', '{"A":"1项","B":"2项","C":"3项","D":"4项"}'::jsonb, '{"choices":["D"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 86, 'single_choice', '2025年10月20日至23日，党的二十届四中全会在北京召开， 研究制定“十五五”规划建议。下列关于习近平如何准确把握阶段性要求，科学谋划“十五五”相关阐述说法不正确的是（    ）。', '{"A":"要前瞻性把握国际形势发展变化对我国的影响，因势利导对经济布局进行调整优化","B":"要坚定不移办好自己的事，坚定不移扩大高水平对外开放","C":"要更加注重统筹发展和安全，通盘考虑内外部风险挑战","D":"要以“绿水青山就是金山银山”的发展理念，发展绿色产业以提升国家竞争力"}'::jsonb, '{"choices":["D"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 87, 'single_choice', '2025年10月20日至23日，党的二十届四中全会在北京召开， 研究制定“十五五”规划建议。下列关于习近平如何准确把握阶段性要求，科学谋划“十五五”相关阐述说法不正确的是（    ）。', '{"A":"对各方面的目标任务，要深入分析论证，确保科学精准、能够如期实现","B":"一个领域一个领域合理确定目标任务、提出思路举措","C":"着眼强国建设、民族复兴伟业，紧紧围绕实现全体人民共同富裕目标","D":"必须准确把握“十五五”时期的阶段性要求"}'::jsonb, '{"choices":["C"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 88, 'single_choice', '“十五五”时期经济社会发展的根本目的是:', '{"A":"实现共同富裕","B":"推动高质量发展","C":"满足人民美好生活需要","D":"建设现代化产业体系"}'::jsonb, '{"choices":["C"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 89, 'single_choice', '加快制造强国建设，要保持制造业合理比重，并培育壮大（    ）产业。', '{"A":"新兴和未来","B":"传统","C":"劳动密集","D":"资源型"}'::jsonb, '{"choices":["A"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 90, 'single_choice', '下列哪项不是全会强调的“十五五”时期国家安全重点（    ）', '{"A":"经济安全","B":"网络数据安全","C":"深层地下水安全","D":"生物安全"}'::jsonb, '{"choices":["C"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 91, 'single_choice', '推进国家安全体系和能力现代化，要提高（    ）体系。', '{"A":"公共安全治理；社会治理","B":"军事装备；国防动员","C":"网络攻防；数据出境","D":"食品药品监管；标准认证"}'::jsonb, '{"choices":["A"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 92, 'single_choice', '全会提出，加快绿色转型，要深入推进（    ）设（    ）体系。', '{"A":"污染防治；新型能源","B":"沙漠治理；储能","C":"垃圾分类；循环农业","D":"退耕还林；碳交易"}'::jsonb, '{"choices":["A"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('单项选择题', 93, 'single_choice', '党的二十届四中全会指出，推进中国式现代化必须增强（    ）', '{"A":"必胜信心","B":"速度意识","C":"规模导向","D":"负债扩张"}'::jsonb, '{"choices":["A"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('多项选择题', 1, 'multiple_choice', '全会高度评价“十四五”时期我国发展取得的重大成就，包括哪些方面？', '{"A":"经济实力、科技实力、综合国力跃上新台阶","B":"中国式现代化迈出新的坚实步伐","C":"第二个百年奋斗目标新征程实现良好开局","D":"全面建成小康社会"}'::jsonb, '{"choices":["A","B","C"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('多项选择题', 2, 'multiple_choice', '全会指出，我国发展具有多方面显著优势，包括哪些？', '{"A":"中国特色社会主义制度优势","B":"超大规模市场优势","C":"完整产业体系优势","D":"丰富人才资源优势"}'::jsonb, '{"choices":["A","B","C","D"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('多项选择题', 3, 'multiple_choice', '“十五五”时期经济社会发展必须遵循的原则（“六个坚持”）包括哪些？', '{"A":"坚持党的全面领导","B":"坚持人民至上","C":"坚持高质量发展","D":"坚持全面深化改革","E":"坚持有效市场和有为政府相结合","F":"坚持统筹发展和安全"}'::jsonb, '{"choices":["A","B","C","D","E","F"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('多项选择题', 4, 'multiple_choice', '全会强调，坚持以党的自我革命引领社会革命，需要增强党的哪些力量？', '{"A":"文化传播力","B":"思想引领力","C":"群众组织力","D":"社会号召力"}'::jsonb, '{"choices":["B","C","D"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('多项选择题', 5, 'multiple_choice', '全会对加快形成新质生产力作出了部署，主要包括哪些方面？', '{"A":"加强原始创新和关键核心技术攻关","B":"推动科技创新和产业创新深度融合","C":"一体推进教育科技人才发展","D":"深入推进数字中国建设"}'::jsonb, '{"choices":["A","B","C","D"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('多项选择题', 6, 'multiple_choice', '全会提出，构建高水平社会主义市场经济体制，需要做哪些工作？', '{"A":"充分激发各类经营主体活力","B":"加快完善要素市场化配置体制机制","C":"提升宏观经济治理效能","D":"立即取消所有市场准入限制"}'::jsonb, '{"choices":["A","B","C"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('多项选择题', 7, 'multiple_choice', '全会提出，加大保障和改善民生力度，应坚持什么原则？', '{"A":"尽力而为","B":"政府包办","C":"量力而行","D":"一步到位"}'::jsonb, '{"choices":["A","C"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('多项选择题', 8, 'multiple_choice', '以下哪些是“十五五”时期在美丽中国建设方面的目标？', '{"A":"美丽中国建设取得新的重大进展","B":"全面建成美丽中国","C":"生态环境根本好转","D":"碳达峰碳中和目标初步实现"}'::jsonb, '{"choices":["A"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('多项选择题', 9, 'multiple_choice', '全会提出，切实抓好灾后哪些工作？', '{"A":"恢复重建","B":"受灾群众安置","C":"生活保障","D":"气候预测"}'::jsonb, '{"choices":["A","B","C"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('多项选择题', 10, 'multiple_choice', '实现社会主义现代化是一个怎样的历史过程？', '{"A":"阶梯式递进","B":"不断发展进步","C":"快速推进","D":"线性发展"}'::jsonb, '{"choices":["A","B"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('多项选择题', 11, 'multiple_choice', '全会指出，加快构建新发展格局，关键在于增强什么？', '{"A":"国内大循环内生动力","B":"国际市场占有率","C":"国内大循环的可靠性","D":"政府投资规模"}'::jsonb, '{"choices":["A","C"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('多项选择题', 12, 'multiple_choice', '以下哪些是“十五五”时期推动经济发展的要求？', '{"A":"经济增长保持在合理区间","B":"全要素生产率稳步提升","C":"居民消费率明显提高","D":"追求超高速增长"}'::jsonb, '{"choices":["A","B","C"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('多项选择题', 13, 'multiple_choice', '全会对收入分配提出了哪些目标？', '{"A":"居民收入增长和经济增长同步","B":"劳动报酬提高和劳动生产率提高同步","C":"中等收入群体持续扩大","D":"迅速消除收入差距"}'::jsonb, '{"choices":["A","B","C"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('多项选择题', 14, 'multiple_choice', '完善区域创新体系的要求是什么？', '{"A":"创新资源集中在发达地区","B":"统筹区域创新资源","C":"形成各具特色、优势互补的区域创新格局","D":"各地区采用相同创新模式"}'::jsonb, '{"choices":["B","C"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('多项选择题', 15, 'multiple_choice', '全会提出，要健全什么样的社会治理制度？', '{"A":"共建","B":"共治","C":"共享","D":"政府包揽"}'::jsonb, '{"choices":["A","B","C"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('多项选择题', 16, 'multiple_choice', '在现代化产业体系建设中，要坚持什么方向？', '{"A":"智能化","B":"绿色化","C":"融合化","D":"粗放化"}'::jsonb, '{"choices":["A","B","C"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('多项选择题', 17, 'multiple_choice', '以下哪些是我国“十五五”时期发展面临的总体环境判断？', '{"A":"战略机遇和风险挑战并存","B":"不确定难预料因素增多","C":"一片坦途，没有挑战","D":"长期向好的支撑条件和基本趋势没有变"}'::jsonb, '{"choices":["A","B","D"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('多项选择题', 18, 'multiple_choice', '“十五五”时期，党领导经济社会发展的目的是什么？', '{"A":"单纯追求经济总量","B":"满足人民日益增长的美好生活需要","C":"推动人的全面发展","D":"推动全体人民共同富裕迈出坚实步伐"}'::jsonb, '{"choices":["B","C","D"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('多项选择题', 19, 'multiple_choice', '全会对全面从严治党提出了什么要求？', '{"A":"持之以恒推进","B":"可以松口气、歇歇脚","C":"为推进中国式现代化凝聚磅礴力量","D":"提高党领导经济社会发展能力和水平"}'::jsonb, '{"choices":["A","C","D"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('多项选择题', 20, 'multiple_choice', '全会要求，在民生建设中要重点解决好什么问题？', '{"A":"宏观政策问题","B":"人民群众急难愁盼问题","C":"国际外交问题","D":"提高人民生活品质"}'::jsonb, '{"choices":["B","D"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('多项选择题', 21, 'multiple_choice', '全会分析了我国发展的多重优势，并指出推进美丽中国建设需要协同推进的工作包括哪些？', '{"A":"我国有超大规模市场、完整产业体系等多重优势","B":"我国已完全克服所有发展风险挑战","C":"需要以降碳为重点战略方向","D":"只需打好污染防治攻坚战即可","E":"推动减污、降碳、扩绿、增长协同增效"}'::jsonb, '{"choices":["A","C","E"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('多项选择题', 22, 'multiple_choice', '关于“十五五”时期的原则和民生工作，下列哪些说法符合全会精神？', '{"A":"坚持党的全面领导是根本保证","B":"民生福利项目应脱离发展阶段，立即达到最高水平","C":"民生工作要坚持“尽力而为、量力而行”","D":"发展是唯一目标，民生可以暂缓","E":"坚持高质量发展是主题"}'::jsonb, '{"choices":["A","C","E"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('多项选择题', 23, 'multiple_choice', '下列哪些表述准确反映了全会关于新发展格局、中国式现代化和对外开放的论述？', '{"A":"构建新发展格局的战略基点是扩大内需","B":"中国式现代化的出发点和落脚点是实现人民对美好生活的向往","C":"要稳步扩大制度型开放","D":"构建新发展格局的关键在于完全依赖国际市场","E":"中国式现代化可以照搬国外模式"}'::jsonb, '{"choices":["A","B","C"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('多项选择题', 24, 'multiple_choice', '根据全会公报，下列哪些说法是正确的？', '{"A":"出席全会的有中央委员和候补中央委员","B":"“十四五”时期发展历程平稳顺利，未经历重大挑战","C":"全会对灾后恢复重建工作作出了部署","D":"“十五五”时期要保持制造业比重快速持续上升","E":"我国经受住了世纪疫情等重大考验"}'::jsonb, '{"choices":["A","C","E"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('多项选择题', 25, 'multiple_choice', '关于全会审议的文件、发展动力和生产力，以下正确的选项有哪些？', '{"A":"全会审议通过了关于“十五五”规划的建议","B":"改革创新是“十五五”时期发展的根本动力","C":"发展新质生产力与巩固壮大实体经济根基相互促进","D":"发展虚拟经济是形成新质生产力的主要途径","E":"国务院主持制定并审议通过了规划《建议》"}'::jsonb, '{"choices":["A","B","C"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('多项选择题', 26, 'multiple_choice', '以下关于“十五五”时期发展要求和工作部署的表述，哪些是正确的？', '{"A":"高质量发展是“十五五”时期经济社会发展的主题","B":"要“保持制造业合理比重”","C":"“十五五”规划《纲要》由国务院主持制定","D":"全会要求保持制造业比重“快速持续上升”","E":"规划《建议》和规划《纲要》的制定主体和程序相同"}'::jsonb, '{"choices":["A","B","C"]}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('填空题', 1, 'fill_blank', '中国共产党第二十届中央委员会第四次全体会议于2025年____月____日至____月____日在北京举行。', null, '{"text":"10；20；10；23"}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('填空题', 2, 'fill_blank', '全会审议通过了《中共中央关于制定国民经济和社会发展第____个五年规划的建议》。', null, '{"text":"十五"}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('填空题', 3, 'fill_blank', '全会强调，“十五五”时期经济社会发展的主题是推动____。', null, '{"text":"高质量发展"}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('填空题', 4, 'fill_blank', '建设现代化产业体系，必须坚持把发展经济的着力点放在____经济上。', null, '{"text":"实体"}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('填空题', 5, 'fill_blank', '构建新发展格局的战略基点是扩大____。', null, '{"text":"内需"}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('填空题', 6, 'fill_blank', '中国式现代化的出发点和落脚点是实现人民对____的向往。', null, '{"text":"美好生活"}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('填空题', 7, 'fill_blank', '全会提出，加大保障和改善民生力度，要坚持____而为、____而行的原则。', null, '{"text":"尽力；量力"}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('填空题', 8, 'fill_blank', '全会要求，坚持以党的____引领社会革命。', null, '{"text":"自我革命"}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('填空题', 9, 'fill_blank', '“十五五”时期在基本实现社会主义现代化进程中，是具有____启后重要地位的关键时期。', null, '{"text":"承前"}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('填空题', 10, 'fill_blank', '全会指出，我国有中国特色社会主义制度优势、超大规模市场优势、完整产业体系优势和丰富____优势。', null, '{"text":"人才资源"}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('填空题', 11, 'fill_blank', '党的二十届四中全会审议通过了《中共中央关于制定国民经济和社会发展第____个五年规划的建议》。', null, '{"text":"十五"}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('填空题', 12, 'fill_blank', '全会提出，要稳步扩大____开放，这是更高水平对外开放的核心内涵。', null, '{"text":"制度型"}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

insert into public.problems (section, source_no, question_type, stem, options, answer, source)
values ('填空题', 13, 'fill_blank', '实现社会主义现代化是一个____递进、不断发展进步、需要不懈奋斗的历史过程。', null, '{"text":"阶梯式"}'::jsonb, 'problems.txt')
on conflict (section, source_no) do update set
  question_type = excluded.question_type,
  stem = excluded.stem,
  options = excluded.options,
  answer = excluded.answer,
  source = excluded.source;

commit;
